# WebDash Config

# The port to start the web server on
# Default: 26666
# IMPORTANT: This port must be open on your firewall
port: 26666
# run `/webdash restart` to apply changes


# The port to start the web socket server on
# Default: 26667
# IMPORTANT: This port must be open on your firewall
# IMPORTANT: This port must be different from the web server port
socket-port: 26667
# run `/webdash restart` to apply changes


# How many characters the dashboard protection key should be
# Default: 200
key-length: 200