name: WebDash
version: '${project.version}'
main: com.simondmc.webdash.WebDash
author: SimonDMC
description: A Web Dashboard for your Minecraft server
website: simondmc.com

commands:
  webdash:
    usage: "§cInvalid usage! Check §e/webdash help §cfor more information."
    aliases: [ wd ]
    permission: webdash.command
    permission-message: §cYou do not have permission to use this command.
permissions:
  webdash.command:
    description: Gives access to the WebDash command
    default: op